## Multiclass Classification using Softmax Layer in TensorFlow

### Importing the required libraries

```python

In [165]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.losses import SparseCategoricalCrossentropy
import pandas as pd
import numpy as np
import matplotlib as plt


### importing Datasets

In [166]:
train_dataset=pd.read_csv("./train.csv")
test_dataset=pd.read_csv("./test.csv")

### Modifying the dataset:

In [167]:
train_df=pd.DataFrame(train_dataset)
test_df=pd.DataFrame(test_dataset)
print(f"Shape of training dataset:{train_df.shape}")
print(f"Shape of test dataset:{test_df.shape}")

Shape of training dataset:(8068, 11)
Shape of test dataset:(2627, 10)


In [168]:
# data types for train_dataset
train_df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [169]:
test_df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
dtype: object

### Removing Null Values

In [170]:
# Checking null values in training dataframe
train_df.isna().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

### Converting non-numeric data to numeric

In [213]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
list=['Gender', 'Ever_Married', 'Graduated', 'Profession', 'Spending_Score',
       'Var_1', 'Segmentation']
for i in list:
    train_df[i]=le.fit_transform(train_df[i])

X_train=train_df.drop('Segmentation',axis=1)
y_train=train_df['Segmentation']

In [223]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.NaN,strategy='mean')
list=['Work_Experience','Family_Size']

for i in list:
    X_train[i]=imp.fit_transform(X_train[i].values.reshape(-1,1))

X_train

ID  Gender  Ever_Married  Age  Graduated  Profession   
0     462809       1             0   22          0           5  \
1     462643       0             1   38          1           2   
2     466315       0             1   67          1           2   
3     461735       1             1   67          1           7   
4     462669       0             1   40          1           3   
...      ...     ...           ...  ...        ...         ...   
8063  464018       1             0   22          0           9   
8064  464685       1             0   35          0           4   
8065  465406       0             0   33          1           5   
8066  467299       0             0   27          1           5   
8067  461879       1             1   37          1           4   

      Work_Experience  Spending_Score  Family_Size  Var_1  
0            1.000000               2          4.0      3  
1            2.641663               0          3.0      3  
2            1.000000               2          1.0      5  
3            0.000000               1          2.0      5  
4            2.641663               1          6.0      5  
...               ...             ...          ...    ...  
8063         0.000000               2          7.0      0  
8064         3.000000               2          4.0      3  
8065         1.000000               2          1.0      5  
8066         1.000000               2          4.0      5  
8067         0.000000               0          3.0      3  

[8068 rows x 10 columns]

In [224]:
print(y_train.isna().sum())
print(y_train.unique())
y_train

0
[3 0 1 2]


0       3
1       0
2       1
3       1
4       0
       ..
8063    3
8064    3
8065    3
8066    1
8067    1
Name: Segmentation, Length: 8068, dtype: int32

In [225]:
test_df.isna().sum()

ID                   0
Gender               0
Ever_Married        50
Age                  0
Graduated           24
Profession          38
Work_Experience    269
Spending_Score       0
Family_Size        113
Var_1               32
dtype: int64

### Model: Using Softmax Layer

In [178]:
model=Sequential([
    Dense(units=25, activation='relu'),
    Dense(units=15, activation='relu'),
    Dense(units=10, activation='softmax') # Assuming there are 10 Classes
])

### Loss and Fit:

In [226]:
model.compile(loss=SparseCategoricalCrossentropy())
model.fit(X_train,y_train, epochs=100)

Epoch 1/100
253/253 [==============================] - 1s 1ms/step - loss: 10929.3584
Epoch 2/100
253/253 [==============================] - 0s 1ms/step - loss: 2147.0923
Epoch 3/100
253/253 [==============================] - 0s 1ms/step - loss: 2158.2009
Epoch 4/100
253/253 [==============================] - 0s 1ms/step - loss: 2109.8201
Epoch 5/100
253/253 [==============================] - 0s 1ms/step - loss: 2120.6958
Epoch 6/100
253/253 [==============================] - 0s 1ms/step - loss: 2081.8137
Epoch 7/100
253/253 [==============================] - 0s 1ms/step - loss: 2075.4766
Epoch 8/100
253/253 [==============================] - 0s 1ms/step - loss: 2054.3059
Epoch 9/100
253/253 [==============================] - 0s 1ms/step - loss: 2040.6315
Epoch 10/100
253/253 [==============================] - 0s 1ms/step - loss: 2008.7146
Epoch 11/100
253/253 [==============================] - 0s 1ms/step - loss: 1964.6154
Epoch 12/100
253/253 [==============================] - 0s 1ms

In [233]:
le=LabelEncoder()
list=['Gender', 'Ever_Married', 'Graduated', 'Profession', 'Spending_Score',
       'Var_1']
for i in list:
    test_df[i]=le.fit_transform(test_df[i])

ID  Gender  Ever_Married  Age  Graduated  Profession   
0     458989       0             1   36          1           2  \
1     458994       1             1   37          1           5   
2     458996       0             1   69          0           9   
3     459000       1             1   59          0           4   
4     459001       0             0   19          0           8   
...      ...     ...           ...  ...        ...         ...   
2622  467954       1             0   29          0           5   
2623  467958       0             0   35          1           1   
2624  467960       0             0   53          1           3   
2625  467961       1             1   47          1           4   
2626  467968       0             0   43          1           5   

      Work_Experience  Spending_Score  Family_Size  Var_1  
0                 0.0               2          1.0      5  
1                 8.0               0          4.0      5  
2                 0.0               2          1.0      5  
3                11.0               1          2.0      5  
4                 NaN               2          4.0      5  
...               ...             ...          ...    ...  
2622              9.0               2          4.0      5  
2623              1.0               2          1.0      5  
2624              NaN               2          2.0      5  
2625              1.0               1          5.0      3  
2626              9.0               2          3.0      6  

[2627 rows x 10 columns]

In [234]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_27 (Dense)            (None, 25)                275       
                                                                 
 dense_28 (Dense)            (None, 15)                390       
                                                                 
 dense_29 (Dense)            (None, 10)                160       
                                                                 
Total params: 825
Trainable params: 825
Non-trainable params: 0
_________________________________________________________________


In [256]:
prediction=model.predict(test_df)
print(prediction)

83/83 [==============================] - 0s 1ms/step
[[ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [nan nan nan ... nan nan nan]
 [ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]]
